# Site
name: "DarkWinterGRUP Blog - The Miracle of Digital Arts | Bir Dijital Sanat Mucizesi"
title: "DarkWinterGRUP Blog - Graphic, Content, WordPress Design & Support Blog"
description: "We will take you on the unique world of exploration. Content, design, snippets, inspiration, wordpress and much more.<br>Eat, Pray, Love!"
logo: 'assets/images/logo-dw.png'
favicon: 'assets/images/favicon.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: darkwintergrup@gmail.com

# Authors
authors:
  darkwintergrup:
    name: DarkWinterGRUP
    display_name: DarkWinterGRUP
    avatar: 'assets/images/dwg-profile.jpg'
    email: darkwintergrup@gmail.com
    web: https://www.instagram.com/darkwintergrup/
    twitter: https://www.instagram.com/darkwintergrup/
    description: "The Miracle of Digital Arts | Bir Dijital Sanat Mucizesi <br>Graphic, Content, WordPress Design & Support Services<br>Freelancer - Contact Mail & Instagram."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
lsi: false
safe: true
incremental: false
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
